### ISSUE TITLE
如果tableView.rowHeight = UITableViewAutomaticDimension,动态高度

### ISSUE THREAD

**Issue by lixiaoyu** [Nododo/AdoHideTableSection#2]
想请教下如果tableView.rowHeight = UITableViewAutomaticDimension,动态高度，咋解决高度保存的问题啊？

**Comment by Nododo** [comment]
暂时没有想到好的解决方法,这里不仅是动态高度,而且还是系统帮你计算的高度...如果你有好的方法可以继续issue

**Comment by lixiaoyu** [comment]
我现在是，根据显示隐藏，把section的row给0或datalist.count
